Repository pingcap/parser, pull requests merged in 2018-12, with the labels that each got.

#59 *: add an shell script to make checkout PR branch easier
  checkout-pr-branch.sh
Labels: LGTM2

#55 ast, parser: extract create view parameters to CreateViewStmt
  ast/ddl.go
  model/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#53 *: support new aggregation function var_pop and var_samp
  ast/functions.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#60 parser: support disable window function parser
  lexer.go
  parser_test.go
  yy_parser.go
Labels: LGTM1

#56 *: support AST to SQL text
  ast/ast.go
  ast/ddl.go
  ast/dml.go
  ast/expressions.go
  ast/expressions_test.go
  ast/functions.go
  ast/misc.go
  ast/stats.go
  ast/util.go
  ast/util_test.go
  go.mod1
  go.sum1
  parser_test.go
Labels: LGTM2

#63 ast: impl Restore of ColunmNameExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM1

#62 ast: implement the Restore function of UseStmt
  ast/misc.go
  parser_test.go
Labels: LGTM2

#68 *: change default charset from utf8 to utf8mb4 (#13)
  charset/charset.go
  mysql/charset.go
  parser.go
  parser.y
  types/field_type.go
Labels: LGTM1, cherry-pick-2.1

#66 charset: make collation case insensitive
  charset/charset.go
  charset/charset_test.go
Labels: LGTM2

#70 charset: make collation case insensitive (#66)
  charset/charset.go
  charset/charset_test.go
Labels: LGTM1, cherry-pick-2.1

#72 parser: ast/expressions.go: IsNullExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#14 *: add ActionModifyTableCharsetAndCollate to support alter table charset and collate
  model/ddl.go
Labels: LGTM2

#75 parser: optimize restore unit test
  ast/expressions_test.go
  ast/util_test.go
Labels: LGTM2

#74 parser,ast: parse ALTER TABLE .. TRUNCATE PARTITION
  ast/ddl.go
  model/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#73 parser: implement Restore for TableName
  ast/dml.go
  ast/dml_test.go
Labels: LGTM2, contribution

#78 parser: add RestoreCtx and change the Node interface
  ast/ast.go
  ast/ddl.go
  ast/dml.go
  ast/expressions.go
  ast/functions.go
  ast/misc.go
  ast/stats.go
  ast/util.go
  ast/util_test.go
  go.mod1
  go.sum1
  opcode/opcode.go
  parser_test.go
Labels: LGTM2

#71 parser: implement Restore for BetweenExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#82 parser: update dependencies
  go.mod1
  go.sum1
Labels: LGTM1

#81 parser: implement Restore for BinaryOperation, WhenClause, CaseExpr and ParenthesesExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM1, contribution

#84 parser: implement Restore for DefaultExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#83 parser: implement Restore for DropIndexStmt
  ast/ddl.go
  parser_test.go
Labels: LGTM2, contribution

#89 parser: implement Restore for PatternLikeExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#90 parser: Implement Restore for IsTruthExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#97 parser: implement Restore for DropStatsStmt
  ast/stats.go
  parser_test.go
Labels: LGTM2, contribution

#88 parser: implement Restore for IndexOption
  ast/ddl.go
  ast/ddl_test.go
  parser.go
  parser.y
Labels: LGTM1, contribution

#100 parser: implement Restore for Limit
  ast/dml.go
  ast/dml_test.go
Labels: LGTM1, contribution

#99 parser: implement Restore for ValuesExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#96 parser: implement Restore for PatternRegexpExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#107 parser: implement Restore for DropTableStmt
  ast/ddl.go
  parser_test.go
Labels: LGTM1, contribution

#103 ci: update ci script for checking code format
  ast/ddl_test.go
  ast/dml_test.go
  circle.yml
Labels: LGTM2

#108 parser: implement Restore for MaxValueExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#106 opcode: fix literal string of operator `EQ`
  ast/expressions_test.go
  opcode/opcode.go
Labels: LGTM1, contribution

#118 parser: implement Restore for WildCardField, SelectField and FieldList
  ast/dml.go
  ast/dml_test.go
Labels: LGTM2, contribution

#98 parser: implement Restore for OnDeleteOpt And OnUpdateOpt
  ast/ddl.go
  ast/ddl_test.go
Labels: LGTM2, contribution

#113 parser: implement Restore for RowExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#91 parser: implement Restore for IndexColName
  ast/ddl.go
  ast/ddl_test.go
Labels: LGTM2, contribution

#111 parser: implement Restore for TableSource and Join
  ast/dml.go
  ast/dml_test.go
  ast/util.go
Labels: LGTM1, contribution

#117 parser: implement Restore for DeleteTableList
  ast/dml.go
  ast/dml_test.go
Labels: LGTM2, contribution

#122 parser: implement Restore for TruncateTableStmt
  ast/ddl.go
  ast/ddl_test.go
Labels: LGTM1, contribution

#101 ignore hint when meet unknow token in hint (#80)(#120)
  ast/format_test.go
  ast/misc_test.go
  bench_test.go
  goyacc/main.go
  lexer.go
  parser.go
  parser.y
  parser_example_test.go
  parser_test.go
  yy_parser.go
Labels: cherry-pick-2.1

#123 implement Restore for ReferenceDef
  ast/ddl.go
  ast/ddl_test.go
Labels: LGTM1, contribution

#121 makefile: add fmt command in Makefile
  Makefile
  circle.yml
Labels: LGTM2, enhancement

#109 parser: implement Restore for TableToTable
  ast/ddl.go
  ast/ddl_test.go
Labels: DNM, LGTM2, contribution

#114 parser: implement Restore for RenameTableStmt
  ast/ddl.go
  parser_test.go
Labels: LGTM1, contribution

#125 parser: implement Restore for PositionExpr, ByItem and GroupByClause
  ast/dml.go
  ast/dml_test.go
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#128 parser: implement Restore for OrderByClause
  ast/dml.go
  ast/dml_test.go
Labels: LGTM2, contribution

#129 parser: implement Restore for HavingClause
  ast/dml.go
  ast/dml_test.go
Labels: LGTM2, contribution

#127 parser: implement Restore for Constraint
  ast/ddl.go
  ast/ddl_test.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#87 parser: implement Restore for VariableExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#131 add drop view ddl action
  model/ddl.go
Labels: contribution
