Repository pingcap/parser, pull requests merged in 2018-11, with the labels that each got.

#9 goyacc: fix unstability of generated parser.go
  Makefile
  goyacc/main.go
  parser.go
Labels: LGTM1

#13 *: change default charset from utf8 to utf8mb4
  charset/charset.go
  mysql/charset.go
  parser.go
  parser.y
  types/field_type.go
Labels: LGTM2

#15 Makefile: fix 'make test'
  Makefile
  go.mod
  go.sum
  mysql/const_test.go
Labels: LGTM2

#10 mysql: NO_AUTO_CREATE_USER detect helper function
  mysql/const.go
Labels: LGTM2

#20 parser,ast: fix the TiDB issue #8153
  ast/expressions.go
  parser.go
  parser.y
Labels: LGTM2

#11 mysql: Update sql mode default
  mysql/const.go
Labels: LGTM2

#24 Revert "parser,ast: fix the TiDB issue #8153 (#20)"
  ast/expressions.go
  parser.go
  parser.y
Labels: LGTM1

#21 parser: support window function grammar
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#23 update README.md, fix `make test`, add circle.yml
  .gitignore
  Makefile
  README.md
  circle.yml
  go.mod1
  go.sum1
  mysql/const_test.go
  test.sh
Labels: LGTM1

#28 README: fix the format
  README.md
Labels: LGTM1

#35 README: add `Go Report Card` and `CircleCI Status` badge
  README.md
Labels: LGTM1

#34 model: add GetAutoIncrementColInfo for TableInfo
  model/model.go
Labels: LGTM2

#22 union: fix union dual table order by
  go.mod1
  go.sum1
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#36 circle.yml: added a step to verify parser.go is up-to-date
  circle.yml
Labels: LGTM1

#37 parser: support window function ast
  ast/dml.go
  ast/dml_test.go
  ast/functions.go
  ast/functions_test.go
  parser.go
  parser.y
Labels: LGTM2

#44 parser: add driver import check & example
  parser_example_test.go
  yy_parser.go
Labels: LGTM2

#42 README: update replace parser version command
  README.md
Labels: LGTM2

#41 parser,ast: support `alter table add partition partitions by hash partitioned table` syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#48 add from_tso function
  ast/functions.go
  parser_test.go
Labels: LGTM2, contribution

#47 Add test case about format "a % b"
  ast/format_test.go
Labels: LGTM2

#49 fix error message print verbs
  mysql/errname.go
Labels: LGTM2

#51 ast: Fix FrameBound.Accept
  ast/dml.go
  parser_test.go
Labels: contribution

#25 Fix variable formatting for ErrTruncateWrongValue
  mysql/errname.go
Labels: LGTM2, contribution

#50 change Tso function name to TiDBParseTso
  ast/functions.go
Labels: LGTM1, contribution
