Repository pingcap/parser, pull requests merged in 2019-06, with the labels that each got.

#343 ast: add new field in create view stmt
  ast/ddl.go
Labels: LGTM2, bugfix

#311 Fix handling of FLOAT(p), FLOAT(m,d) and DECIMAL(m,0) types esp. w.r.t. Restore()
  ast/ddl_test.go
  parser.go
  parser.y
  parser_test.go
  types/field_type.go
Labels: LGTM1

#305 *: try to support lock/unlock tables function
  ast/ddl.go
  model/ddl.go
  model/model.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, enhancement

#345 *: support parsing all PARTITION BY syntax
  ast/ddl.go
  ast/expressions_test.go
  misc.go
  model/model.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
  terror/terror.go
Labels: LGTM1

#351 model: add in union flag
  model/flags.go
Labels: enhancement

#350 *: support syntax for 'admin reload expr_pushdown_blacklist'
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#355 *: support syntax for 'admin reload expr_pushdown_blacklist' (#350)
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: cherry-pick-3.0

#337 *: add `IF EXISTS` and `IF NOT EXISTS` supported for MariaDB
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#323 *: add admin cleanup table lock syntax support
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#362 add `split table ... between ... and` syntax (#321)
  ast/dml.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, cherry-pick-2.1

#366 parser: fix hint parsing in `select /*+ max_execution_time */ 1`
  parser.go
  parser.y
  parser_test.go
Labels: bugfix
