Repository pingcap/parser, pull requests merged in 2019-09, with the labels that each got.

#533 parser: fix CREATE INDEX .. TYPE syntax
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#530 parser: fix obscure error message in `bit(65)` column type
  parser.go
  parser.y
Labels: LGTM1, PTAL

#398 *: add where for show table region syntax
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: enhancement

#541 executor: cache point get plan for prepared point
  ast/misc.go
Labels: LGTM2, enhancement

#546 parser: add missing generated column related mysql errors
  mysql/errcode.go
  mysql/errname.go
Labels: LGTM1, PTAL

#540 parser: fix SQL_TSI_YEAR column type syntax
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#548 fix CONSTRAINT syntax
  ast/ddl.go
  ast/ddl_test.go
  ast/misc_test.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#536 parser: fix *TEXT BYTE | ASCII | UNICODE syntax
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#550 add IGNORE_INDEX hint
  ast/misc.go
  ast/misc_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#559 cherry-pick sql hint related PRs into release-3.1
  ast/dml.go
  ast/misc.go
  ast/misc_test.go
  circle.yml
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#562 parser: optimize performance
  goyacc/main.go
  parser.go
  yy_parser.go
Labels: LGTM2

#556 parser: fix FIXED syntax
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#563 parser: add support for STORAGE DEFAULT/DISK/MEMORY in column attributes
  ast/ddl.go
  ast/ddl_test.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#514 add `idxInMulti` to `ExecStmt` to support prepare multiple sql
  ast/misc.go
Labels: LGTM2
