Repository pingcap/parser, pull requests merged in 2019-02, with the labels that each got.

#166 Add PR and Issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
Labels: LGTM2

#163 parser: tiny update README.md
  README.md
Labels: LGTM2

#197 parser: implement Restore for CreateUserStmt, AlterUserStmt and DropUserStmt
  ast/dml.go
  ast/misc.go
  auth/auth.go
  parser_test.go
Labels: LGTM2, contribution

#193 parser: implement Restore for PrepareStmt ExplainStmt ExecuteStmt Dea…
  ast/misc.go
  parser_test.go
Labels: LGTM2, contribution

#199 parser: implement Restore for VariableAssignment, SetStmt and SetPwdStmt
  ast/misc.go
  parser_test.go
Labels: LGTM2, contribution

#196 parser: implement Restore for BinlogStmt, FlushStmt, KillStmt, DoStmt and AdminStmt
  ast/misc.go
  parser_test.go
Labels: LGTM2, contribution

#192 parser: support OPTIONALLY keyword in LOAD DATA
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#198 parser: implement Restore for PrivElem, GrantStmt and RevokeStmt
  ast/misc.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#203 parser: minor fix of #198
  ast/misc.go
  parser_test.go
Labels: LGTM1, contribution

#32 support sql digest
  digester.go
  digester_test.go
  lexer.go
Labels: LGTM1

#167 parser: implement Restore for TraceStmt
  ast/misc.go
  parser_test.go
Labels: LGTM2, contribution

#208 parser: fix lexer that treat 9eTSs as a float
  lexer.go
  lexer_test.go
  parser_test.go
Labels: LGTM2, bugfix

#210 model: add IsAutoIncColUnsigned for TableInfo (#79)
  model/model.go
Labels: LGTM1, cherry-pick-2.1, enhancement

#209 plugin: add `flush tidb plugins [plugin-name,..]` support
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#206 parser: finish the restore function of all ast node
  ast/ddl.go
  ast/dml.go
  ast/misc.go
  go.mod1
  go.sum1
  mysql/const.go
  parser_test.go
  types/field_type.go
Labels: LGTM2

#211 parser: parse the fraction of CURRENT_TIMESTAMP default value
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#93 parser: add 'INSTANT' alter algorithm
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#217 parser: add support for `show pump/drainer status`
  ast/dml.go
  misc.go
  parser.go
  parser.y
Labels: LGTM2, contribution

#216 parser: add CreateRolePriv and DropRolePriv
  mysql/const.go
  parser.go
  parser.y
Labels: LGTM2

#221 parser: fix stored option in generated column restore
  ast/ddl.go
  ast/ddl_test.go
  mysql/const.go
Labels: LGTM2, bugfix

#215 normalize and generate digest at same time
  digester.go
  digester_test.go
Labels: LGTM2

#223 model: add version field to tableInfo.
  model/model.go
Labels: LGTM2

#225 model: add version field to tableInfo. (#223)
  model/model.go
Labels: LGTM1, cherry-pick-2.1

#194 parser: support generated column related mysql errors
  mysql/errcode.go
  mysql/errname.go
Labels: LGTM1

#219 ast: add `create role` ast structure
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2
