Repository pingcap/parser, pull requests merged in 2019-11, with the labels that each got.

#592 Support full-text search
  ast/dml.go
  ast/dml_test.go
  ast/expressions.go
  ast/expressions_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/new-feature

#612 parser: add error number for store limit error
  mysql/errcode.go
  mysql/errname.go
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2

#614 mysql: add error code for types
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1

#615 mysql: add error code and message for table related to error
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1

#616 3.0 support nowait grammar
  ast/dml.go
  ast/util.go
  misc.go
  model/model_test.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: type/3.0 cherry-pick

#618 clean up error code and message for parser
  charset/charset.go
  types/etc.go
  yy_parser.go
Labels: status/LGT1

#619 support hint for indexMergeJoin and indexHashJoin
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/new-feature

#620 parser: support drop specific plan binding
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/new-feature

#617 *: support add/drop primary key
  model/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2, type/new-feature

#629 ast/functions: add tidb_decode_plan() function (#557)
  ast/functions.go
  parser_test.go
Labels: status/LGT2, type/3.1 cherry-pick, type/enhancement

#628 terror: add error class `ClassUtil`
  terror/terror.go
Labels: status/LGT2

#610 Add Cloud Spanner style read only transaction
  ast/dml.go
  ast/expressions.go
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#626 parser: add a mysql error message (#534)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1, type/3.0 cherry-pick

#627 parser: add a mysql error message (#534)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2, type/3.1 cherry-pick

#625 parser: add a mysql error message (#534)
  mysql/errcode.go
  mysql/errname.go
Labels: type/2.1 cherry-pick

#631 parser: replace magic numbers with meaningful names (#531)
  mysql/const.go
  parser.go
  parser.y
Labels: type/2.1 cherry-pick

#633 parser: replace magic numbers with meaningful names (#531)
  mysql/const.go
  parser.go
  parser.y
Labels: type/3.1 cherry-pick

#634 sysvar: error code for sysvar.go in tidb
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1, type/enhancement

#630 mysql: add ddl-related error code and name
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2, type/enhancement

#635 parser : add error number for store limit error (#612)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1

#637 parser : add error number for store limit error (#612)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2

#638 parser: add mysql error `ErrIncorrectType`
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2

#639 parser : add errcode and errname for admin repair table.
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2

#641 *: bump the Go compiler version to 1.13
  circle.yml
  go.mod1
Labels: status/LGT1, type/enhancement

#640 *: support primary key (#617)
  model/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/3.0 cherry-pick

#632 parser: replace magic numbers with meaningful names (#531)
  mysql/const.go
  parser.go
  parser.y
Labels: status/LGT2, type/3.0 cherry-pick

#636 parser : add error number for store limit error (#612)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2, type/3.0 cherry-pick

#622 parser: fix obscure error message in `bit(65)` column type (#530)
  parser.go
  parser.y
Labels: status/LGT2, type/2.1 cherry-pick

#623 parser: fix obscure error message in `bit(65)` column type (#530)
  parser.go
  parser.y
Labels: status/LGT2, type/3.0 cherry-pick

#643 cherry-pick sql hint related PRs into release-3.1.6 (#559)
  ast/dml.go
  ast/misc.go
  ast/misc_test.go
  circle.yml
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: type/3.1 cherry-pick, type/enhancement

#642 Fix compatibility for `OnUpdate`, `OnDelete` and other clauses (#331, #392, #393)
  ast/ddl.go
  ast/ddl_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: status/LGT1, type/3.0 cherry-pick

#646 parser: support syntax for manage bindings
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/new-feature

#644 parser: add mysql error `ErrBadUser` / `ErrUserAlreadyExists`
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1

#647 Fix compatibility for `OnUpdate`, `OnDelete` and other clauses (#331, #392, #393) (#642)
  ast/ddl.go
  ast/ddl_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: type/3.1 cherry-pick

#648 parser: fix SET=DEFAULT syntax (#551)
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/3.0 cherry-pick

#566 fix alter table convert to charset default syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: contribution, status/LGT2

#521 parser: fix tableAlias in `DeleteStmt`
  parser.go
  parser.y
  parser_test.go
Labels: contribution, status/LGT2, status/can merge

#650 add error code from planner, expression and executor
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1, type/enhancement
