Repository pingcap/parser, pull requests merged in 2019-10, with the labels that each got.

#570 add support for SHOW BUILTINS syntax.
  ast/dml.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#569 parser, ast: fix the TiDB issue #8153 (#27)
  ast/expressions.go
Labels: LGTM2, cherry-pick-2.1

#568 *: support where in admin show ddl statement
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, enhancement

#572 support CREATE VIEW ... UnionStmt
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#574 support CREATE VIEW ... UnionStmt (#572)
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, cherry-pick-3.0

#573 support CREATE VIEW ... UnionStmt (#572)
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, cherry-pick-3.1

#561 *: refine split region syntax add split partition table region syntax.
  ast/dml.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: DNM, LGTM1

#565 parser: parse the fraction of CURRENT_TIMESTAMP default value (#211)
  parser.go
  parser.y
Labels: LGTM2, bugfix, cherry-pick-2.1

#579 .github: add CODEOWNER rule to request review for PRs automatically
  .github/CODEOWNERS
Labels: LGTM2, enhancement

#581 remove GrantPriv from AllGlobalPrivs/AllDBPrivs/AllTablePrivs
  mysql/const.go
  mysql/const_test.go
Labels: LGTM2, contribution

#583 ast/functions: add tidb_decode_plan() function (#557)
  ast/functions.go
  parser_test.go
Labels: LGTM2, cherry-pick-3.0

#567 fix SET CHARSET | NAMES DEFAULT
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#547 parser : support admin repair table syntax
  ast/ddl.go
  ast/ddl_test.go
  model/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#564 *: suport alter table set flash replica syntax
  ast/ddl.go
  misc.go
  model/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#580 parser: add support for SHUTDOWN syntax
  ast/misc.go
  ast/misc_test.go
  misc.go
  mysql/const.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#539 ast: fix the bug of TableSource.Restore()
  ast/dml.go
  ast/dml_test.go
Labels: contribution, status/LGT2

#585 mysql: add write conflict error
  mysql/errcode.go
  mysql/errname.go
Labels: type/2.1 cherry-pick, type/enhancement

#575 ast: add `CachedNames` for Prepared
  ast/misc.go
Labels: status/LGT2, status/PTAL

#586 parser: support database name for optimizer hint
  ast/misc.go
  ast/misc_test.go
  parser.go
  parser.y
Labels: status/LGT2

#587 Fixed: failed to parse WHERE / GROUP BY clauses in a SELECT statement without a FROM table
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1

#590 parser: improve index merge hint
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#588 makefile: add copy action from go.mod1 to go.mod
  Makefile
Labels: status/LGT2

#589 parser: support FLUSH LOGS | HOSTS syntax
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#584 mysql: add some errors for TiDB
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2

#593 *: bump the Go compiler version to 1.13
  circle.yml
  go.mod1
  go.sum1
Labels: status/LGT2, type/enhancement

#591 parser: rename 'timestampliteral' to avoid misuse of 'select timestampliteral()'
  ast/format_test.go
  ast/functions.go
  parser_test.go
Labels: status/LGT1

#595 mysql: add 2 infoschema related errors for TiDB
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2, status/can merge, type/enhancement

#597 revert pr 587 failed to parse WHERE / GROUP BY clauses in a SELECT statement without a FROM table
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/compatibility
