Repository pingcap/parser, pull requests merged in 2019-05, with the labels that each got.

#288 parser: Refine LoadDataStmt
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#314 *: fix upper-cased charset and collation name (#301)
  charset/charset.go
  charset/charset_test.go
  model/model.go
  mysql/charset.go
  parser.go
  parser.y
Labels: cherry-pick-2.1

#313 digester: avoid infinite loop when an invalid token is seen
  digester.go
  digester_test.go
Labels: LGTM1, bugfix

#315 type/compatibility: fix show create table output of generated column
  ast/functions_test.go
  parser.go
  parser.y
Labels: LGTM1, cherry-pick-2.1

#297 *: Add split index region syntax support.
  ast/dml.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#318 parser: add support for `ALTER DATABASE` syntax
  ast/ddl.go
  ast/ddl_test.go
  model/ddl.go
  model/model_test.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, enhancement

#316 parser: support mysql-compatible explain format
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#324 test: enable coverage when running unit tests
  .gitignore
  README.md
  circle.yml
  test.sh
Labels: LGTM2

#327 parser: add support for `ALTER DATABASE` syntax (#318)
  ast/ddl.go
  ast/ddl_test.go
  model/ddl.go
  model/model_test.go
  parser.go
  parser.y
  parser_test.go
Labels: cherry-pick-2.1

#319 errcode.go: Add ErrBadUser
  mysql/errcode.go
Labels: LGTM2

#312 Support load data ignore replace
  ast/ddl.go
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#334 mysql: add write conflict error for latch and change the error code of ErrTxnTooLarge
  mysql/errcode.go
  mysql/errname.go
Labels: LGTM1

#335 support keyword `OPTIMISTIC` and `PESSIMISTIC`.
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#338 ast: fix case expression format bug
  ast/expressions.go
  ast/format_test.go
Labels: bugfix

#339 Add mysql standard error code 1907
  mysql/errcode.go
  mysql/errname.go
Labels: LGTM1

#317 *: add "show open tables" support (#291)
  ast/dml.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, cherry-pick-2.1

#304 Parser: Support SQL_BIG_RESULT, SQL_SMALL_RESULT, SQL_BUFFER_RESULT
  ast/dml.go
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#342 Fix several lexer bugs involving special comments
  lexer.go
  parser_test.go
Labels: LGTM2

#240 Add ErrInvalidJSONPathArrayCell
  mysql/errcode.go
  mysql/errname.go
Labels: LGTM2, contribution
