Repository pingcap/parser, pull requests merged in 2019-08, with the labels that each got.

#421 Fix AST.Restore() restore char(1) to char(1,0)
  types/field_type.go
Labels: LGTM2

#418 add support for SECONDARY_ENGINE
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#422 model: add schema name, table name to ddl job
  model/ddl.go
Labels: LGTM2

#142 ast,parser: added several expression types to represent keyword arguments
  ast/ddl.go
  ast/dml.go
  ast/functions.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#433 add support for RTREE index
  misc.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, component/compatibility, contribution

#425 parser: support cast as real
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, enhancement

#440 parser: support analyze options for samples
  ast/stats.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: enhancement

#397 parser: add opt_rule_blacklist and `admin reload` it (#375)
  ast/misc.go
  misc.go
  parser.go
  parser.y
Labels: LGTM2, cherry-pick-3.0

#442 add support for PASSWORD EXPIRE
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, PTAL, component/compatibility, contribution

#455 parser: fix `IF NOT EXISTS` support for MariaDB `ADD PARTITION` syntax
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#450 Fix CREATE DATABASE … ENCRYPTION syntax
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#452 add support for INSERT_METHOD
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#456 parser: Fix NO_WRITE_TO_BINLOG option for ALTER TABLE Partition Operations syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#465 parser: fix CHARACTER VARYING syntax
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#466 attempt to fix MATCH syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#458 remove executable on parser_test.go
  parser_test.go
Labels: LGTM2, contribution

#449 add support for EXCHANGE PARTITION
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#441 parser.y: fix variable in set, 'set xx.xx = 42' is a valid statement
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, bugfix

#424 parser: add several optimizer hints
  ast/misc.go
  ast/misc_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#473 parser: fix LONG syntax
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#454 add support for CREATE [UNIQUE | FULLTEXT | SPATIAL] INDEX
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#471 parser: Support keyword `FIELDS` in `ALTER TABLE PARTITION BY` syntax
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#453 add support for [TRUNCATE|DISCARD|IMPORT|OPTIMIZE|REPAIR] PARTITION
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#457 parser: Fix CHECK PARTITION syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#469 Support ALTER TABLE REBUILD PARTITION syntax
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#484 Support DROP INDEX ... [ALGORITHM | LOCK] syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#488 fix: add support for TABLE_CHECKSUM
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#489 add support for ALTER TABLE ... RENAME syntax
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#487 add stmtType to ast.Prepared to record metric
  ast/misc.go
Labels: LGTM2

#495 parser: support `SQL_TSI_*`
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#493 Remove `%prec` annotation on keyword `CHARSET`
  parser.y
Labels: LGTM1

#482 Support COLUMN_FORMAT syntax.
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#494 parser: support REORGANIZE PARTITION syntax
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#483 parser: fix STATS_AUTO_RECALC syntax
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#505 parser: support `ALTER TABLE ALTER CHECK`, `ALTER TABLE DROP CHECK` syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#496 parser: support `secondary_load` and `secondary_unload`
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#504 add support for ALTER TABLE ... RENAME COLUMN syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#481 Support keyword `SERIAL`
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#515 parser: fix VARCHARACTER, VARYING syntax
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#516 parser: fix LOCK clause error message
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#513 change memory quota hint argument
  ast/misc.go
  ast/misc_test.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#517 parser: add agg_to_cop hint
  ast/misc.go
  ast/misc_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#446 add a table hint to access table from a specific type of storage.
  ast/misc.go
  ast/misc_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#512 parser: Fix DISCARD/IMPORT TABLESPACE syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#511 ast: add stmtType to ast.Prepared to record metric (#487)
  ast/misc.go
Labels: LGTM2, cherry-pick-2.1

#518 Fix CREATE INDEX .. VISIBLE/INVISIBLE syntax
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#492 make begin/commit/rollback/set be traceable
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, LGTM2

#520 parser: support table option: 'ENCRYPTION'
  ast/ddl.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#510 ast: add stmtType to ast.Prepared to record metric (#487)
  ast/misc.go
Labels: LGTM2, cherry-pick-3.0

#523 parser: support table option 'UNION'
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#524 Parser: support with parser ident
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#519 add support for ALTER TABLE ... ALTER INDEX syntax
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#522 ast: change the order of visiting select stmt
  ast/dml.go
Labels: LGTM2
