Repository pingcap/parser, pull requests merged in 2019-04, with the labels that each got.

#267 model: add FindIndexByName function
  model/model.go
Labels: LGTM2

#268 parser: fix error message for illegal year type definition.
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: LGTM1, contribution

#270 types: port 'HasCharset' function from MySQL
  types/field_type.go
  types/field_type_test.go
Labels: LGTM1

#269 Parser: Support CREATE USER extensions per MySQL 5.7
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, contribution

#252 model: add MaxShardRowIDBits to table info to record the max ShardRowIDBits be used so far
  model/model.go
Labels: LGTM2

#260 parser, ast: add ColumnOptionCollate for all column types
  ast/ddl.go
  ast/ddl_test.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#248 mysql/charset.go: Add quick path to avoid access map
  mysql/charset.go
Labels: LGTM1

#271 ast: support `EXPLAIN FOR CONNECTION`
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#180 change `admin restore table` syntax to `recover table` syntax.
  ast/ddl.go
  ast/misc.go
  misc.go
  model/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#279 normalize and generate digest at same time (#215)
  digester.go
  digester_test.go
  lexer.go
Labels: LGTM1, cherry-pick-2.1

#274 parser: fix load data syntax
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, contribution

#273 parser: refine error messages that are inconsistent with MySQL
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: LGTM2

#283 types: port 'HasCharset' function from MySQL (#270)
  types/field_type.go
  types/field_type_test.go
Labels: cherry-pick-2.1

#276 add drop view ddl action (#131)
  model/ddl.go
Labels: LGTM2, cherry-pick-2.1

#277 ast,parser: fix misspell
  ast/dml.go
  parser.y
Labels: LGTM2

#275 parser: complete Restore for CreateUserStmt
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#272 ast: add role support show grant
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#256 improve:GetCharsetDesc
  charset/charset.go
  charset/charset_test.go
Labels: LGTM2, contribution

#287 *: add table option: pre_split_regions
  ast/ddl.go
  misc.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#291 *: Add "show open tables" support
  ast/dml.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, component/compatibility

#290 parser, ast: add ColumnOptionCollate for all column types (#260)
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: cherry-pick-2.1

#235 type/compatibility: fix show create table output of generated column
  ast/expressions.go
  ast/expressions_test.go
  ast/functions.go
  ast/functions_test.go
  ast/util_test.go
  format/format.go
  parser.go
  parser.y
  parser_test.go
  types/field_type.go
Labels: LGTM1, contribution

#214 fix now frac in column option
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#294 suspend unknown collation id 255 error
  charset/charset.go
Labels: LGTM2

#282 parser: support incremental analyze
  ast/stats.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#292 parser: support show analyze status
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, enhancement

#296 suspend unknown collation id 255 error (#294)
  charset/charset.go
Labels: LGTM1, cherry-pick-2.1

#295 charset: add GetSupportedCollations to get only supported collations
  charset/charset.go
  charset/charset_test.go
  model/model.go
  mysql/charset.go
Labels: LGTM2

#201 parser: check invalid column define option for generated columns
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#306 parser: add charset validation (TiDB #4436) (#220)
  ast/functions_test.go
  goyacc/main.go
  lexer.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: LGTM2, cherry-pick-2.1

#307 Add begin lock syntax for pessimistic transaction.
  ast/misc.go
  parser.go
  parser.y
Labels: LGTM2

#298 Parser: Support SHOW PROFILE Syntax
  ast/dml.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2
