Repository pingcap/parser, pull requests merged in 2019-07, with the labels that each got.

#367 parser: parse SQL statement to the last character
  lexer.go
  lexer_test.go
Labels: LGTM2

#349 *: add show table regions syntax
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#371 parser: fix hint parsing in `select /*+ max_execution_time */ 1` (#366)
  parser.go
  parser.y
  parser_test.go
Labels: cherry-pick-3.0

#368 *: support syntax for 'admin reload expr_pushdown_blacklist' (#350)
  ast/dml.go
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: cherry-pick-2.1

#365 add `hexLit` and `binaryList` support for `LOAD DATA`
  ast/misc.go
  go.mod1
  go.sum1
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#372 model: add LoadData statement flag
  model/flags.go
Labels: LGTM1

#373 mysql: add a new state `ErrInvalidJSONPathArrayCell`
  mysql/state.go
Labels: LGTM2

#377 test: count coverage for all packages when unit testing
  test.sh
Labels: LGTM2

#379 parser: support "admin plugins enable/disable plugin" syntax (#374)
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: cherry-pick-3.0

#382 Do not compile unit test in parallel
  test.sh
Labels: LGTM1

#381 utils: `IsReadOnly` returns wrong result when checking SQLs like `explain analyze insert ...`
  ast/util.go
  ast/util_test.go
Labels: LGTM2, bugfix

#380 parser: support "admin plugins enable/disable plugin" syntax (#374)
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, cherry-pick-2.1

#384 *: add show table regions syntax (#349)
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: cherry-pick-3.0

#375 parser: add opt_rule_blacklist and `admin reload` it.
  ast/misc.go
  misc.go
  parser.go
  parser.y
Labels: LGTM1, cherry-pick-3.0, enhancement

#391 *: add `Not` flag for `ExistsSubqueryExpr`
  ast/expressions.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, cherry-pick-2.1, enhancement

#386 parser: parse and ignore 'PARTITION BY LIST ..."
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, cherry-pick-2.1

#383 parser: support DELETE FROM ... AS ... syntax
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#333 Issue 332 support "DROP TEMPORARY table"
  ast/ddl.go
  ast/ddl_test.go
  parser.go
  parser.y
Labels: LGTM1, contribution

#389 charset: add 'char set' syntax support
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#331 issues 280: Support ON UPDATE ddl statements
  ast/ddl_test.go
  parser.go
  parser.y
Labels: LGTM2, contribution

#392 parser: support some new syntax
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: LGTM2, component/compatibility

#394 parser: add TableOptimizerHint TIDB_HASHAGG and TIDB_STREAMAGG
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#388 parser: support more analyze options
  ast/stats.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, enhancement

#393 parser: fix compatibility for `OnDelete`,`OnUpdate` clauses
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#401 parser : add support for octet_length function
  ast/functions.go
Labels: LGTM1, contribution

#396 parser: fix remove partitioning syntax
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, component/compatibility

#399 parser: support cast as double
  mysql/util.go
  parser.go
  parser.y
  parser_test.go
  types/field_type.go
Labels: LGTM1, enhancement

#407 add support for STORAGE table option
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: component/compatibility, contribution, enhancement

#414 add support for STATS_SAMPLE_PAGES
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, component/compatibility, contribution, enhancement

#400 *: make 'grant all privileges' work right
  ast/misc.go
  mysql/const.go
  mysql/const_test.go
  parser.go
  parser.y
  parser_test.go
Labels: bugfix

#416 parser: support cast as float
  mysql/util.go
  parser.go
  parser.y
  parser_test.go
  types/field_type.go
  yy_parser.go
Labels: LGTM2, enhancement
