Repository pingcap/parser, pull requests merged in 2019-01, with the labels that each got.

#135 parser: implement Restore for FrameBound
  ast/dml.go
  ast/dml_test.go
  ast/util_test.go
  parser.go
  parser.y
Labels: LGTM2, contribution

#144 parser: implement Restore for BeginStmt,CommitStmt,RollbackStmt, AnalyzeTableStmt and LoadStatsStmt
  ast/misc.go
  ast/stats.go
  parser_test.go
Labels: LGTM2, contribution

#76 ast, mysql: add window function flag and error message
  ast/ast.go
  ast/flag.go
  mysql/errcode.go
  mysql/errname.go
Labels: LGTM2, enhancement

#102 parser: implement Restore for FuncCallExpr and AggregateFuncExpr
  ast/functions.go
  ast/functions_test.go
  ast/util_test.go
  types/field_type.go
Labels: LGTM2, contribution

#148 parser: support `show create database if not exists` syntax
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, enhancement

#143 parser: implement Restore for FrameClause, PartitionByClause, WindowSpec and WindowFuncExpr
  ast/dml.go
  ast/dml_test.go
  ast/functions.go
  ast/functions_test.go
Labels: LGTM2, contribution

#133 parser: better error message
  lexer.go
  parser_test.go
Labels: LGTM2, contribution

#45 mysql: update sql-mode default
  mysql/const.go
Labels: LGTM2

#152 *: add ActionModifyTableCharsetAndCollate to support alter table charset and collate (#14)
  model/ddl.go
Labels: LGTM2, cherry-pick-2.1

#157 parser: change the location of RestoreCtx
  ast/ast.go
  ast/ddl.go
  ast/dml.go
  ast/expressions.go
  ast/functions.go
  ast/misc.go
  ast/stats.go
  ast/util.go
  ast/util_test.go
  format/format.go
  format/format_test.go
  go.mod1
  go.sum1
  parser_test.go
Labels: DNM, LGTM2, contribution

#156 parser: add show create user syntax
  ast/dml.go
  parser.go
  parser.y
Labels: LGTM2, contribution

#159 parser: upload tidb version
  go.mod1
  go.sum1
Labels: LGTM1

#162 parser: fix tidb version
  go.mod1
  go.sum1
Labels: LGTM2

#160 parser: implement Restore for ColumnOption, FieldType and ColumnDef
  ast/ddl.go
  ast/ddl_test.go
  ast/expressions.go
  opcode/opcode.go
  types/field_type.go
Labels: LGTM2

#168 parser: implement Restore for InsertStmt
  ast/dml.go
  parser_test.go
Labels: LGTM1, contribution

#154 parser: implement Restore for AlterTableStmt and AlterTableSpec
  ast/ddl.go
  ast/ddl_test.go
  ast/util_test.go
  parser_test.go
Labels: LGTM2, contribution

#161 add support binding for sql
  ast/dml.go
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: DNM, LGTM2, contribution

#150 parser: implement Restore for CreateIndexStmt
  ast/ddl.go
  ast/ddl_test.go
  parser_test.go
Labels: LGTM2, contribution

#153 parser: implement Restore for SelectStmt
  ast/dml.go
  ast/dml_test.go
  ast/expressions.go
  ast/functions.go
  ast/functions_test.go
  ast/misc.go
  ast/misc_test.go
  ast/util_test.go
  opcode/opcode.go
  parser_test.go
Labels: LGTM2, contribution

#173 mysql,terror: add plugin error msg
  mysql/errcode.go
  mysql/errname.go
  terror/terror.go
Labels: LGTM1

#171 mysql: add sql mode ALLOW_INVALID_DATES
  mysql/const.go
Labels: LGTM2, contribution

#164 support select partition syntax
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#172 support restore table by table name syntax.
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#174 parser: fix subquery in PatternInExpr.Restore and add tests
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM1, contribution

#170 parser: implement Restore for CreateTableStmt
  ast/ddl.go
  ast/ddl_test.go
  ast/util_test.go
  parser_test.go
  types/field_type.go
Labels: LGTM2, contribution

#181 parser,ast: parse ALTER TABLE .. TRUNCATE PARTITION (#74)
  ast/ddl.go
  model/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, cherry-pick-2.1

#182 ci: fix integration test of ci
  circle.yml
Labels: LGTM2, bugfix

#126 parser: implement Restore for ExistsSubqueryExpr
  ast/expressions.go
  ast/expressions_test.go
Labels: LGTM2, contribution

#169 parser: fix window function interval expression type
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#185 mysql: add sql mode ALLOW_INVALID_DATES (#171)
  mysql/const.go
Labels: cherry-pick-2.1, contribution

#178 parser: implement Restore for ShowStmt
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, contribution

#184 parser: implement Restore for LoadDataStmt
  ast/dml.go
  parser_test.go
Labels: LGTM1, contribution

#177 parser: add show create view grammar
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#175 improve syntax error message
  circle.yml
  lexer.go
  mysql/errname.go
  parser_test.go
  yy_parser.go
Labels: LGTM1

#190 parser: implement restore for UpdateStmt
  ast/dml.go
  parser_test.go
Labels: LGTM2, contribution

#189 implement Restore for DeleteStmt
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, contribution

#138 parser: add CreateViewPriv privilege
  mysql/const.go
  parser.go
  parser.y
Labels: LGTM2, contribution
