Repository pingcap/parser, pull requests merged in 2019-03, with the labels that each got.

#227 auth: use safe String() for UserIdentity
  auth/auth.go
Labels: LGTM2

#222 Support parsing TokuDB storage engine's ROW_FORMAT
  ast/ddl.go
  ast/ddl_test.go
  misc.go
  parser.go
  parser.y
  terror/terror_test.go
Labels: LGTM2, contribution

#229 auth: use safe String() for UserIdentity (#227)
  auth/auth.go
Labels: LGTM2, cherry-pick-2.1

#232 mysql: change MySQL version from 5.7.10 to 5.7.25
  mysql/const.go
Labels: cherry-pick-2.1

#231 mysql: change MySQL version from 5.7.10 to 5.7.25
  mysql/const.go
Labels: enhancement

#200 types: Fix description for year type
  types/field_type.go
  types/field_type_test.go
Labels: LGTM2

#236 ast: fix the behavior of window function
  ast/dml.go
  ast/dml_test.go
  ast/functions_test.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1, enhancement

#234 parser: parse 'partition by linear hash' and ignore it
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#243 Support update pump or drainer status
  ast/misc.go
  ast/misc_test.go
  misc.go
  parser.go
  parser.y
Labels: LGTM2, contribution

#233 *: parser subpartition option for 'partition by range columns'
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2

#247 improve: GetAllCharsets and GetCharsetInfoByID
  charset/charset.go
Labels: LGTM2, contribution

#226 ast: fix return err value in Restore (#224)
  ast/dml.go
Labels: LGTM2, contribution

#228 parser, ast: add `SET ROLE` support
  ast/functions.go
  ast/misc.go
  auth/auth.go
  go.sum1
  misc.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#242 ast: add GrantRoleStmt to support `GRANT ROLE`
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM1

#250 *: skip 'go mod tidy' check in integration test
  circle.yml
Labels: LGTM1

#253 update tidb dep version and fix cycle dep in test
  export_test.go
  go.mod1
  go.sum1
  parser_test.go
Labels: LGTM2

#251 *: fix type of MaxInt64
  parser_test.go
  yy_parser.go
Labels: bugfix, contribution

#257 mysql,terror: add plugin error msg (#173)
  mysql/errcode.go
  mysql/errname.go
  terror/terror.go
Labels: LGTM2, cherry-pick-2.1

#259 support show pump/drainer status && change pump/drainer's status
  ast/dml.go
  ast/misc.go
  ast/misc_test.go
  misc.go
  parser.go
  parser.y
Labels: LGTM2, cherry-pick-2.1

#258 model: increase table and column version (#254)
  model/model.go
Labels: LGTM1

#262 plugin: add `flush tidb plugins [plugin-name,..]` support (#209)
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, cherry-pick-2.1

#263 fix key work node_id && node_state
  consistent_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, bugfix

#264 fix key word node_id and node_state
  consistent_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: LGTM2, bugfix, cherry-pick-2.1

#220 parser: add charset validation (TiDB #4436)
  ast/functions_test.go
  goyacc/main.go
  lexer.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: LGTM2, contribution
