Repository pingcap/parser, pull requests merged in 2019-12, with the labels that each got.

#652 add hint for (no_)swap_join_inputs
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/enhancement

#621 model: add hidden to ColumnInfo
  ast/dml.go
  misc.go
  model/model.go
  model/model_test.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, status/PTAL, type/new-feature

#654 ast: support explain format hint
  ast/misc.go
  parser_test.go
Labels: status/LGT2

#655 remove an unnecessary variable
  misc.go
Labels: status/LGT2

#611 *: support flashback truncate table.
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#659 model: add a function GetTypeDesc for ColumnInfo
  model/model.go
Labels: status/LGT2

#660 model: add a function GetTypeDesc for ColumnInfo (#659)
  model/model.go
Labels: status/LGT2

#662 model: add a function GetTypeDesc for ColumnInfo (#659)
  model/model.go
Labels: status/LGT1

#663 *: refine split region syntax add split partition table region syntax (#561)
  ast/dml.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: type/3.0 cherry-pick

#656 parser: introduce DigestNormalized and deprecate DigestHash
  digester.go
  digester_test.go
Labels: type/bug-fix

#665 remove GrantPriv from AllGlobalPrivs/AllDBPrivs/AllTablePrivs (#581)
  mysql/const.go
  mysql/const_test.go
Labels: status/LGT1

#658 DDL : add create sequence support & compatible with mariaDB except OrReplace.
  ast/ddl.go
  ast/ddl_test.go
  misc.go
  model/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: help wanted, status/LGT2

#668 parser: introduce DigestNormalized and deprecate DigestHash (#656)
  digester.go
  digester_test.go
Labels: type/3.0 cherry-pick, type/bug-fix

#669 parser: introduce DigestNormalized and deprecate DigestHash (#656)
  digester.go
  digester_test.go
Labels: type/3.1 cherry-pick, type/bug-fix

#664 ddl: add expression index support
  ast/ddl.go
  ast/ddl_test.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/new-feature

#671 mysql: update some TiDB customized error code
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2, type/enhancement

#571 parser: support syntax for AUTO_RANDOM
  ast/ddl.go
  ast/ddl_test.go
  lexer.go
  lexer_test.go
  misc.go
  model/model.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: status/LGT1

#666 support require clauses in `grant` stmt
  ast/misc.go
  mysql/const.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1

#675 mysql: add foreign key error
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2

#676 remove testleak
  auth/auth_test.go
  charset/charset_test.go
  format/format_test.go
  terror/terror_test.go
  types/field_type_test.go
Labels: status/LGT2

#681 parser : support add show create sequence.
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#679 remove dependency on TiDB
  README.md
  ast/expressions_test.go
  ast/functions_test.go
  ast/util_test.go
  go.mod1
  go.sum1
  parser_example_test.go
  parser_test.go
  test_driver/test_driver.go
  test_driver/test_driver_datum.go
  test_driver/test_driver_helper.go
  test_driver/test_driver_mydecimal.go
  types/field_type_test.go
Labels: status/LGT2

#682 rename go.mod1 to go.mod
  .gitignore
  go.mod
  go.sum
  test.sh
Labels: status/LGT2

#680 parser : support drop sequence syntax.
  ast/ddl.go
  ast/ddl_test.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1

#685 add support for PASSWORD EXPIRE (#442)
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/3.0 cherry-pick, type/compatibility

#686 *: make 'grant all privileges' work right (#400)
  ast/misc.go
  mysql/const.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/3.0 cherry-pick

#688 parser: add support for SHUTDOWN syntax (#580)
  ast/misc.go
  ast/misc_test.go
  misc.go
  mysql/const.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/3.0 cherry-pick

#690 mysql: add foreign key error (#675)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2

#691 parser : Add model & errcode & errname for supporting sequence.
  model/model.go
  model/model_test.go
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1, type/new-feature

#695 mysql: add foreign key error (#675)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1

#696 add auto_random error definitions
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2

#693 terror: replace sirupsen/logrus by pingcap/log
  circle.yml
  codecov.yml
  go.mod
  go.sum
  terror/terror.go
  terror/terror_test.go
  types/field_type_test.go
Labels: status/LGT2, type/enhancement

#697 add `GlobalDBVisible` to represent global privilege which can see all database
  mysql/const.go
Labels: status/LGT2

#698 support require clauses in `grant` stmt (#666)
  ast/misc.go
  mysql/const.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/3.0 cherry-pick

#699 define 'language' as an unreserved keyword
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1

#694 parser: fix panic when MEMORY_QUOTA overflows int64
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: status/LGT2, type/bug-fix

#700 Add parsing of window function for aggregate function varpop
  parser.go
  parser.y
Labels: status/LGT1

#703 Remove abandon command in Makefile
  Makefile
Labels: status/PTAL

#701 add yacc file formatter
  Makefile
  goyacc/format_yacc.go
  goyacc/main.go
  parser.go
  parser.y
Labels: status/LGT2

#702 fix json field name in #571
  model/model.go
Labels: status/LGT2

#705 fix rename column rule
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2
