Repository pingcap/parser, pull requests merged in 2020-06, with the labels that each got.

#882 parser: cherry-pick #868, #856, #836, #855 to 4.0-itai
  ast/dml.go
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#881 parser: cherry-pick #871, #850 to 4.0-itai
  ast/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#880 parser: support partition in table hint
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  hintparser_test.go
  misc.go
Labels: status/LGT1

#879 support `require SAN` clause (#877)
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/4.0-cherry-pick

#875 README.md: update links about joining slack
  README.md
Labels: status/LGT1

#883 Add more fields in DiffSchema for exchanging partition
  model/ddl.go
Labels: status/LGT2

#890 model: correct the usage of json.Unmarshal in DecodeArgs
  model/ddl.go
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2, type/bug-fix

#892 fix charset alias in case function (#891)
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/4.0-cherry-pick

#893 add hint `nth_plan` for plan test.
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  misc.go
  parser_test.go
Labels: status/LGT2

#900 parser: cherry-pick #889 to 4.0-itai
  model/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#896 model: correct the usage of json.Unmarshal in DecodeArgs (#890)
  model/ddl.go
Labels: status/LGT1, type/3.0-cherry-pick

#897 model: correct the usage of json.Unmarshal in DecodeArgs (#890)
  model/ddl.go
Labels: status/LGT1, type/3.1-cherry-pick

#898 model: correct the usage of json.Unmarshal in DecodeArgs (#890)
  model/ddl.go
Labels: status/LGT1, type/2.1-cherry-pick

#895 model: correct the usage of json.Unmarshal in DecodeArgs (#890)
  model/ddl.go
Labels: status/LGT1, type/4.0-cherry-pick

#904 model: add `OriginDefaultValueBit` field to `ColumnInfo`
  model/model.go
  model/model_test.go
Labels: status/LGT2

#818 Add hint for broadcast join.
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  misc.go
  parser_test.go
Labels: status/LGT2, status/can-merge

#884 docs: rewrite quickstart.md
  docs/quickstart.md
Labels: status/LGT1
