Repository pingcap/parser, pull requests merged in 2020-08, with the labels that each got.

#958 parser: cherry-pick #952, #947 and #927 to release-4.0
  model/model.go
Labels: status/LGT2

#966 model: add ChangeStateInfo to ColumnInfo
  model/model.go
Labels: status/LGT2

#978 model: add StateReplicaOnly type to string
  model/model.go
Labels: status/LGT2

#981 parser: add topn_to_cop hint
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  misc.go
  parser_test.go
Labels: status/LGT2

#983 model: fix null origin default value for bit column
  model/model.go
  model/model_test.go
Labels: status/LGT2

#970 model: add DroppingDefinitions for PartitionInfo
  model/model.go
Labels: contribution, status/LGT3

#989 terror: add stack trace in terror log
  terror/terror.go
Labels: needs-cherry-pick-4.0, status/LGT3

#993 terror: add stack trace in terror log (#989)
  terror/terror.go
Labels: status/LGT2, type/4.0-cherry-pick
