Repository pingcap/parser, pull requests merged in 2020-10, with the labels that each got.

#1053 parser: support alter sequence (#1046)
  ast/ddl.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#1052 model: add an extra field on Job for passing argumens
  model/ddl.go
Labels: contribution, status/LGT2

#1061 ast: Don't write comma when restore TableOption of ALTER TABLE
  ast/ddl.go
  ast/ddl_test.go
Labels: status/LGT1

#1049 model: add `OriginDefaultValueBit` field to `ColumnInfo` (#904)
  model/model.go
  model/model_test.go
Labels: status/LGT2, type/4.0-cherry-pick

#1051 *: redact arguments for Error
  charset/charset.go
  go.mod
  go.sum
  hintparserimpl.go
  mysql/errname.go
  mysql/error.go
  mysql/error_test.go
  terror/terror.go
  types/etc.go
  yy_parser.go
Labels: status/LGT2

#1065 model: fix null origin default value for bit column (#983)
  model/model.go
  model/model_test.go
Labels: status/LGT2, type/4.0-cherry-pick

#1058 collation: add new pinyin collation utf8mb4_zh_pinyin_tidb_as_cs
  charset/charset.go
Labels: contribution, status/LGT3

#1055 ast: add explain format=json
  ast/misc.go
Labels: status/LGT2

#1050 model: add `OriginDefaultValueBit` field to `ColumnInfo` (#904)
  model/model.go
  model/model_test.go
Labels: status/LGT2, status/can-merge, type/3.0-cherry-pick
