Repository pingcap/parser, pull requests merged in 2020-01, with the labels that each got.

#706 distinguish 'convert to' keyword in table option of charset
  ast/ddl.go
  ast/ddl_test.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#709 mysql: add 2 infoschema related errors for TiDB (#595)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2, type/3.0 cherry-pick

#710 merge release 3.0 to release 3.1
  ast/dml.go
  ast/misc.go
  ast/misc_test.go
  digester.go
  digester_test.go
  misc.go
  mysql/const.go
  mysql/const_test.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1

#711 Rewrite special comment parser
  Makefile
  codecov.yml
  digester.go
  goyacc/main.go
  hintparser.go
  hintparser.y
  hintparser_test.go
  hintparserimpl.go
  lexer.go
  lexer_test.go
  misc.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: status/LGT2, status/PTAL, type/enhancement

#708 parser: add Reload and File privileges
  misc.go
  mysql/const.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#378 add definition of json_objectagg
  ast/functions.go
  ast/functions_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: contribution, status/LGT2

#716 *: suport alter table set flash replica syntax (#564)
  ast/ddl.go
  go.mod1
  misc.go
  model/ddl.go
  model/model.go
  model/model_test.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/3.1 cherry-pick

#717 Parser: Database and Table encryption (#599 #600)
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: status/LGT2

#713 parser: support sequence function & next value for
  ast/expressions.go
  ast/functions.go
  ast/functions_test.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#723 parser: support syntax for AUTO_RANDOM (#571)
  ast/ddl.go
  ast/ddl_test.go
  lexer.go
  lexer_test.go
  misc.go
  model/model.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: status/LGT2, type/3.1 cherry-pick

#724 fix json field name in #571 (#702)
  model/model.go
Labels: status/LGT2, type/3.1 cherry-pick

#721 Release 3.1 cherry pick tiflash and table lock
  ast/ddl.go
  misc.go
  model/ddl.go
  model/model.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/3.1 cherry-pick

#725 add auto_random error definitions (#696)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2, type/3.1 cherry-pick

#726 add json_objectagg's null key errcode
  mysql/errcode.go
  mysql/errname.go
  mysql/state.go
Labels: status/LGT2

#727 add json_objetagg's unsupported second argument type errorcode
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2
