Repository pingcap/parser, pull requests merged in 2020-07, with the labels that each got.

#918 fix: correct file permission
  ast/ast.go
  ast/expressions.go
  ast/functions.go
  ast/misc.go
  ast/stats.go
  ast/util.go
  ast/util_test.go
  format/format.go
  format/format_test.go
Labels: status/LGT2, status/can-merge

#917 model: add Global field to IndexInfo
  model/model.go
Labels: status/LGT1

#922 types: fix restore cast as binary
  parser_test.go
  types/field_type.go
Labels: needs-cherry-pick-4.0, status/LGT1

#923 types: fix restore cast as binary (#922)
  parser_test.go
  types/field_type.go
Labels: status/LGT2, type/4.0-cherry-pick

#927 parser: add a state field for partitionDefinition
  model/model.go
Labels: status/LGT2

#928 Unreserved 5 keywords (#851)
  consistent_test.go
  go.mod1
  go.sum1
  parser.go
  parser.y
  parser_test.go
  reserved_words_test.go
Labels: status/LGT2, type/3.0-cherry-pick

#929 Unreserved 5 keywords (#851)
  consistent_test.go
  go.mod1
  go.sum1
  parser.go
  parser.y
  parser_test.go
  reserved_words_test.go
Labels: status/LGT2, type/3.1-cherry-pick

#933 parser: support group_concat as window function in parser (#766)
  parser.go
  parser.y
Labels: status/LGT2

#932 parser: support group_concat as window function in parser (#766)
  parser.go
  parser.y
Labels: status/LGT2

#944 fix: remove TypeDecimal
  mysql/type.go
  types/etc.go
  types/field_type.go
Labels: status/LGT1

#930 terror: add terror api to support add and product error workaround automaticly
  terror/terror.go
Labels: status/LGT2

#947 parser: substitute `state` field with `addingDefinition` in partitionInfo
  model/model.go
Labels: status/LGT2

#948 quickstart.md: get dependency with git hash instead of version tag
  docs/quickstart.md
Labels: status/LGT2

#950 Add hint for broadcast join. (#818)
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  misc.go
  parser_test.go
Labels: status/LGT1

#952 parser: append replica-only state to previous one strictly
  model/model.go
Labels: status/LGT2, type/bug-fix
