Repository pingcap/parser, pull requests merged in 2020-09, with the labels that each got.

#991 Add std and stddev function (#972)
  ast/functions.go
  ast/functions_test.go
  parser.go
  parser.y
  parser_test.go
Labels: status/can-merge, type/3.0-cherry-pick

#1004 Fix syntax error caused by unexpected hint
  lexer.go
  parser_test.go
Labels: status/LGT2

#1000 model: support columar table
  model/model.go
Labels: status/LGT1, type/new-feature

#986 yy_parser: enable supportWindowFunc by default
  yy_parser.go
Labels: status/LGT2

#1008 const: fix wrong SQL mode const
  mysql/const.go
  mysql/const_test.go
Labels: needs-cherry-pick-3.0, needs-cherry-pick-4.0, status/LGT2, status/PTAL, status/can-merge, type/bug-fix

#1003 *: fix string(int) issues for Go 1.15 compatibility
  ast/ddl.go
  lexer_test.go
Labels: contribution, status/LGT2, status/can-merge

#1011 parser: support partition in table hint (#880)
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  hintparser_test.go
  misc.go
Labels: status/LGT2, type/4.0-cherry-pick

#1005 parser: add new function name IsTruthWithNull
  ast/functions.go
Labels: needs-cherry-pick-3.0, needs-cherry-pick-4.0, status/LGT1, status/WIP

#1007 ast: Change the implementation of Accept for DefaultExpr
  ast/expressions.go
Labels: needs-cherry-pick-4.0, status/LGT1, type/bug-fix

#1013 Revert "ast: Change the implementation of Accept for DefaultExpr"
  ast/expressions.go
Labels: status/LGT1

#982 using standard error code to replace terror
  go.mod
  go.sum
  terror/terror.go
  terror/terror_test.go
Labels: needs-cherry-pick-4.0, status/LGT2

#1014 using standard error code to replace terror (#982)
  go.mod
  go.sum
  terror/terror.go
  terror/terror_test.go
Labels: type/4.0-cherry-pick

#1016 Rename is truth to IsTruthWithoutNull
  ast/functions.go
Labels: status/LGT1

#1015 fix incorrect convert function restore
  ast/functions.go
  ast/functions_test.go
Labels: contribution, status/LGT3, status/can-merge

#1019 Revert "using standard error code to replace terror (#982)"
  go.mod
  go.sum
  terror/terror.go
  terror/terror_test.go
Labels: status/LGT1

#1010 model: support add extra partition ID column
  model/model.go
Labels: contribution, status/LGT2

#1018 quickstart.md: fix typo
  docs/quickstart.md
Labels: status/LGT2, status/can-merge

#1023 yy_parser: use the default SQL mode when create a new parser.
  parser_test.go
  yy_parser.go
Labels: status/LGT2

#1028 parser: rename topn_to_cop hint to limit_to_cop hint.
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  misc.go
  parser_test.go
Labels: status/LGT1

#1032 fix CreateTablespacePriv order in const
  mysql/const.go
Labels: contribution, status/LGT2

#1025 parser: add new function name IsTruthWithNull (#1005)
  ast/functions.go
Labels: status/LGT1

#1027 ast: Change the implementation of Accept for DefaultExpr
  ast/expressions.go
Labels: status/LGT1, type/bug-fix

#1024 parser: add new function name IsTruthWithNull (#1005)
  ast/functions.go
Labels: DNM, status/LGT2

#1037 parser: introduce a new hint `limit_to_cop`
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  misc.go
  parser_test.go
Labels: status/LGT2, type/4.0-cherry-pick

#1031 model: add SQL mode and warnings field for ddl job
  model/ddl.go
Labels: status/LGT2

#1039 parser: introduce a new hint `set_var`
  ast/misc.go
  hintparser.go
  hintparser.y
  hintparser_test.go
Labels: status/LGT2

#1038 expression: Support `bin-to-uuid` and `uuid-to-bin`
  ast/functions.go
  parser_test.go
Labels: status/LGT2

#1041 types: allows more types to be equal
  types/field_type.go
Labels: status/LGT1

#1042 ddl: *support list column partition table
  model/model.go
Labels: status/LGT2, status/can-merge
