Repository pingcap/parser, pull requests merged in 2020-04, with the labels that each got.

#790 digest: fix '/' in normalizing SQL
  digester_test.go
  lexer.go
Labels: type/bug-fix, type/compatibility

#791 parser: sequence order option parse warning
  parser.go
  parser.y
Labels: status/LGT1

#792 opcode,ast: fix invalid restore of '4 DIV 2' (became '4DIV2')
  ast/expressions.go
  ast/expressions_test.go
  opcode/opcode.go
  opcode/opcode_test.go
Labels: needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2, type/bug-fix

#796 parser: remove sequence order option support
  ast/ddl.go
  ast/ddl_test.go
  misc.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#795 parser: remove with/without validation unsupported warning in parser
  parser.go
  parser.y
Labels: status/LGT2

#765 parser: add autoid cache option
  ast/ddl.go
  misc.go
  model/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: needs-cherry-pick-2.1, needs-cherry-pick-3.0, needs-cherry-pick-3.1, status/LGT2

#803 terror: print the stack in terror.Log()
  terror/terror.go
  terror/terror_test.go
Labels: status/LGT2

#805 Add builtin function prototype `get_mvcc_info` in parser
  ast/functions.go
  parser_test.go
Labels: status/LGT2

#809 fix type conversion panic from NUM to int64
  goyacc/format_yacc.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: status/LGT2

#811 model: add schema name, table name to ddl job (#422)
  model/ddl.go
Labels: type/3.0-cherry-pick

#813 parser: add order by clause in group_concat
  ast/functions.go
  ast/functions_test.go
  parser.go
  parser.y
  parser_test.go
Labels: status/can-merge, type/new-feature

#810 Rewrite special comment parser (#711)
  Makefile
  ast/misc.go
  ast/misc_test.go
  digester.go
  goyacc/main.go
  hintparser.go
  hintparser.y
  hintparser_test.go
  hintparserimpl.go
  lexer.go
  lexer_test.go
  misc.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
  yy_parser.go
Labels: status/LGT2, type/3.1-cherry-pick

#814 add stale error code/msg
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2, type/2.1-cherry-pick

#806 parser: add autoid cache option (#765)
  ast/ddl.go
  misc.go
  model/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#816 add stale error code/msg
  mysql/errcode.go
  mysql/errname.go
Labels: type/3.1-cherry-pick

#815 add stale error code/msg
  mysql/errcode.go
  mysql/errname.go
Labels: type/3.0-cherry-pick

#821 parser: support using dash('-') in config item names
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/enhancement

#822 Add some tests for ‘ignore_plan_cache’, and correct a bug in parser.y
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#823 parser: add auto_random table option support
  ast/ddl.go
  model/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1

#828 parser: rename auto rand table option
  ast/ddl.go
  misc.go
  model/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, status/LGT2, type/new-feature

#827 *: try to support lock/unlock tables function (#305)
  ast/ddl.go
  model/ddl.go
  model/model.go
  mysql/errcode.go
  mysql/errname.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/3.0-cherry-pick

#819 lexer: replace version comments with feature-ids mechanism (#777)
  lexer.go
  lexer_test.go
  misc.go
  yy_parser.go
Labels: type/3.1-cherry-pick

#831 parser: add auto_random_base table option
  ast/ddl.go
  misc.go
  model/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/4.0-cherry-pick

#830 parser: add auto_random_base table option
  ast/ddl.go
  misc.go
  model/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/3.1-cherry-pick

#824 Update BACKUP/RESTORE syntax to match the RFC; Added IMPORT statement
  ast/dml.go
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#834 parser: change `CONFIG` to an unreserved keyword #833
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, status/can-merge, type/bug-fix

#835 parser: introduce a new privilege for the `set config` statement
  mysql/const.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/enhancement

#807 parser: add autoid cache option (#765)
  ast/ddl.go
  misc.go
  model/ddl.go
  model/model.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, status/can-merge

#825 Remove unnecessary `.(string)` casting and `$$ = $1` from parser.y
  parser.go
  parser.y
Labels: status/LGT2, type/enhancement

#838 lexer: replace version comments with feature-ids mechanism (#777)
  lexer.go
  lexer_test.go
  misc.go
  yy_parser.go
Labels: status/LGT1, type/3.0-cherry-pick

#841 types: Update `FieldType.Equal` safety.
  types/field_type.go
  types/field_type_test.go
Labels: status/LGT2
