Repository pingcap/parser, pull requests merged in 2020-03, with the labels that each got.

#754 *: Add format_bytes and format_nano_time function
  ast/functions.go
  parser_test.go
Labels: status/LGT2

#755 parser: set `UnionStmt` and `ShowStmt` as readonly
  ast/util.go
  ast/util_test.go
Labels: status/LGT2

#756 parser: set `UnionStmt` and `ShowStmt` as readonly (#755)
  ast/util.go
  ast/util_test.go
Labels: status/LGT2, type/3.0-cherry-pick, type/bug-fix

#759 support alter instance reload tls (#740)
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: needs-cherry-pick-3.0, status/LGT2

#761 *: set charset and collate for string literals correctly
  ast/expressions.go
  ast/expressions_test.go
  ast/functions_test.go
  ast/misc_test.go
  parser.go
  parser.y
  test_driver/test_driver.go
  test_driver/test_driver_datum.go
Labels: status/LGT2

#762 *: remove useless IndexToProto,ColumnToProto,ColumnsToProto functions
  model/model.go
  model/model_test.go
Labels: status/LGT1

#758 README.md, docs: add an introduction to parser
  README.md
  docs/quickstart.md
  docs/update-parser-for-tidb.md
Labels: status/LGT2, status/can-merge

#766 parser: support group_concat as window function in parser
  parser.go
  parser.y
Labels: status/LGT2, status/can-merge

#769 parser: add USE_CASCADES hint syntax
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  hintparser_test.go
  misc.go
  parser_test.go
Labels: contribution, status/LGT1

#771 model: add invisible option for IndexInfo
  model/model.go
Labels: status/LGT2

#746 *: support parsing BACKUP and RESTORE statements
  ast/dml.go
  ast/functions.go
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/enhancement

#770 parser: support `set config ...` and `show config ...` syntaxes
  ast/dml.go
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/new-feature

#775 rename `sm_join` to `merge_join`
  ast/misc.go
  ast/misc_test.go
  hintparser.y
  hintparser_test.go
  misc.go
  parser_test.go
Labels: status/LGT2

#779 add require secure transport error
  mysql/errcode.go
  mysql/errname.go
Labels: type/3.0-cherry-pick

#781 model: add schema name, table name to ddl job (#422)
  model/ddl.go
Labels: type/3.1-cherry-pick

#780 add require secure transport error (#779)
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT1, type/3.1-cherry-pick

#784 *: Add new ddl action ActionAddColumns
  model/ddl.go
  model/model_test.go
Labels: status/LGT2

#782 parser: recognize BACKUP … SNAPSHOT = TSO in additional to SNAPSHOT = 'TIMESTAMP'
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, status/LGT2

#785 Change hint "enable_plan_cache(bool)" to "ignore_plan_cache()"
  ast/misc.go
  hintparser.go
  hintparser.y
  hintparser_test.go
  misc.go
  parser_test.go
Labels: status/LGT2

#787 parser: add syntax ADMIN RELOAD BINDINGS
  ast/misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/enhancement, type/new-feature

#777 lexer: replace version comments with feature-ids mechanism
  lexer.go
  lexer_test.go
  misc.go
  yy_parser.go
Labels: type/compatibility, type/enhancement

#789 support 'binary' collation in table option
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2
