Repository pingcap/parser, pull requests merged in 2020-12, with the labels that each got.

#1089 Adding vitess_hash function to ast
  ast/functions.go
Labels: first-time-contributor, status/LGT2

#1080 model: add functionality to check if a base table
  model/model.go
  model/model_test.go
Labels: needs-cherry-pick-4.0, status/LGT2

#1104 model: Add StateGlobalTxnWriteOnly
  model/model.go
  model/model_test.go
Labels: status/LGT2, status/can-merge

#1117 spm: fix create binding for update with hint
  lexer.go
  parser_test.go
Labels: needs-cherry-pick-4.0, status/LGT2, type/bug-fix

#1088 mysql: add consts for auth switch request
  mysql/const.go
Labels: status/LGT2

#1120 Manually cherry-pick #1117 to release 4.0
  lexer.go
  parser_test.go
Labels: status/LGT2

#1124 ast: fix restore panic for TRIM() when arguments contain column name
  ast/functions.go
  ast/functions_test.go
Labels: needs-cherry-pick-4.0, status/LGT2, type/bug-fix

#1126 ast: fix restore panic for TRIM() when arguments contain column name (#1124)
  ast/functions.go
  ast/functions_test.go
Labels: status/LGT2

#1128 digester: keep the singleAtIdentifier in normalize
  digester.go
  digester_test.go
Labels: needs-cherry-pick-4.0, status/LGT2, type/bug-fix

#1132 lexer: treat dot differently in different context
  lexer.go
  lexer_test.go
  parser_test.go
Labels: status/LGT2, status/can-merge

#1135 lexer: reset identifierDot to false in QuotedIdent
  lexer.go
  parser_test.go
Labels: status/LGT2, status/can-merge

#1130 digester: keep the singleAtIdentifier in normalize (#1128)
  digester.go
  digester_test.go
Labels: status/LGT2, type/4.0-cherry-pick, type/bug-fix

#1139 util: Add PrepareStmt into readOnly
  ast/util.go
  ast/util_test.go
Labels: status/LGT2
