Repository pingcap/parser, pull requests merged in 2020-02, with the labels that each got.

#731 parser: support expression restored string in default value.
  model/model.go
Labels: status/LGT2

#732 add .editorconfig
  .editorconfig
Labels: status/LGT1

#737 mysql: sort the error code
  mysql/errcode.go
Labels: status/LGT1, type/enhancement

#733 *: refine flashback syntax by remove until timestamp statement.
  ast/ddl.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/enhancement

#738 add `show table $table_name next_row_id` syntax
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: contribution, status/LGT2

#739 parser: add errcode and errname of unsupported sequence default value for column type
  mysql/errcode.go
  mysql/errname.go
Labels: status/LGT2, type/enhancement

#741 mysql/errname.go: update error message of ErrCantGetValidID
  mysql/errname.go
Labels: status/LGT2

#740 support `alter instance reload tls`
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1

#742 model: add partition replica available info to support partition table in tiflash.
  model/model.go
Labels: status/LGT2

#743 parser: add WEIGHT_STRING() function
  ast/functions.go
  ast/functions_test.go
  misc.go
  parser.go
  parser.y
Labels: status/LGT1, type/enhancement

#745 parser: support the `SELECT ... INTO OUTFILE` syntax
  ast/dml.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/new-feature

#747 refine table optimizer hint and make it more generic
  ast/misc.go
  ast/misc_test.go
  hintparser.go
  hintparser.y
  hintparser_test.go
  misc.go
  parser_test.go
Labels: status/LGT2, type/enhancement

#750 README.md: add a user list
  README.md
Labels: status/LGT2

#749 parser, ast: add `SetCollationExpr`
  ast/expressions.go
  ast/functions_test.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/enhancement

#748 misc: correct TiDB-style executable comment version for auto_random
  lexer_test.go
  misc.go
Labels: status/LGT2

#752 model: do not rewrite collation id as default for tipb.
  model/model.go
  model/model_test.go
Labels: type/enhancement

#751 parser, ast: accept syntax about `chain`, `release` when commit or rollback
  ast/misc.go
  misc.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2
