Repository pingcap/parser, pull requests merged in 2020-05, with the labels that each got.

#840 parser: add new ddl action AlterIndexVisibility
  ast/ddl.go
  model/ddl.go
  parser.go
  parser.y
Labels: status/LGT2

#847 parser: add order by clause in group_concat (#813)
  ast/functions.go
  ast/functions_test.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, status/can-merge, type/3.0-cherry-pick, type/new-feature

#849 parser: add order by clause in group_concat (#813)
  ast/functions.go
  ast/functions_test.go
  parser.go
  parser.y
  parser_test.go
Labels: type/4.0-cherry-pick, type/new-feature

#848 parser: add order by clause in group_concat (#813)
  ast/functions.go
  ast/functions_test.go
  parser.go
  parser.y
  parser_test.go
Labels: type/3.1-cherry-pick, type/new-feature

#845 parser: support TableOptimizerHints in InsertStmt
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2

#850 model: add IsCommonHandle field on TableInfo
  model/model.go
Labels: status/LGT1

#842 ast: implement SensitiveStmtNode for BRIEStmt
  ast/misc.go
  ast/misc_test.go
Labels: status/LGT2, type/enhancement

#858 support the syntax insert into tbl_name partition (#856)
  ast/dml.go
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT1, type/4.0-cherry-pick

#859 support show table partition regions (#855)
  parser.go
  parser.y
  parser_test.go
Labels: type/4.0-cherry-pick

#861 parser: support using dash('-') in config item names
  parser.go
  parser.y
  parser_test.go
Labels: needs-cherry-pick-4.0, type/enhancement

#862 parser: change `CONFIG` to an unreserved keyword
  parser.go
  parser.y
  parser_test.go
Labels: type/4.0-cherry-pick, type/enhancement

#863 parser: introduce a new privilege for the `set config` statement
  mysql/const.go
  parser.go
  parser.y
  parser_test.go
Labels: type/4.0-cherry-pick, type/enhancement

#864 fix ci
  circle.yml
Labels: status/LGT2

#870 parser: support partition selection grammer for the delete statement (#868)
  parser.go
  parser.y
  parser_test.go
Labels: status/LGT2, type/4.0-cherry-pick

#797 [3.0] opcode,ast: fix invalid restore of '4 DIV 2' (became '4DIV2') (#792)
  ast/expressions.go
  ast/expressions_test.go
  opcode/opcode.go
  opcode/opcode_test.go
Labels: status/LGT2, type/3.0-cherry-pick

#800 [3.1] opcode,ast: fix invalid restore of '4 DIV 2' (became '4DIV2') (#792)
  ast/expressions.go
  ast/expressions_test.go
  opcode/opcode.go
  opcode/opcode_test.go
Labels: status/LGT2, type/3.1-cherry-pick
