Repository pingcap/parser, pull requests merged in 2020-11, with the labels that each got.

#1072 *: tiny optimize for huge partition table
  model/model.go
Labels: status/LGT2

#1076 *: tiny optimize for huge partition table (#1072)
  model/model.go
Labels: status/LGT2

#1079 Update the errors dependence to the latest version
  go.mod
  go.sum
  terror/terror.go
  yy_parser.go
Labels: status/LGT1

#1083 *: redact arguments for Error (#1051)
  ast/ddl.go
  charset/charset.go
  go.mod
  go.sum
  hintparserimpl.go
  lexer_test.go
  mysql/errname.go
  mysql/error.go
  mysql/error_test.go
  terror/terror.go
  types/etc.go
  yy_parser.go
Labels: status/LGT1

#1084 Update the errors dependence to the latest version (#1079)
  go.mod
  go.sum
  terror/terror.go
  yy_parser.go
Labels: status/LGT1, type/4.0-cherry-pick

#1086 ast: visit Update / Delete as well for CreateBindingStmt / DropBindingStmt
  ast/misc.go
Labels: status/LGT1, type/enhancement

#1091 ast: fix Restore for INL_HASH_JOIN / INL_MERGE_JOIN hints
  ast/misc.go
  ast/misc_test.go
Labels: DNM, needs-cherry-pick-4.0, status/LGT2, type/bug-fix

#1090 model: fix null origin default value for bit column (#983)
  model/model.go
  model/model_test.go
Labels: status/LGT2

#1098 ast: fix Restore for INL_HASH_JOIN / INL_MERGE_JOIN hints (#1091)
  ast/misc.go
  ast/misc_test.go
Labels: status/LGT2, type/4.0-cherry-pick, type/bug-fix

#1093 mysql: fix wrong default decimal length
  mysql/util.go
Labels: status/LGT2

#1040 digester: consider paramMarker as literal when normalizing SQL
  digester.go
  digester_test.go
Labels: needs-cherry-pick-4.0, status/LGT1, type/bug-fix

#1103 digester: consider paramMarker as literal when normalizing SQL (#1040)
  digester.go
  digester_test.go
Labels: status/LGT1

#1096 terror: remove dead code which may cause data race
  terror/terror.go
Labels: status/LGT2, status/can-merge

#1105 *: add a flag `RestoreWithDefaultDB` for Restore
  ast/dml.go
  format/format.go
Labels: status/LGT1

#1108 types: fix incorrect `show create table` when the flen is 0 for char and varchar
  types/field_type.go
  types/field_type_test.go
Labels: status/LGT2

#1106 ast: Change the implementation of Accept for DefaultExpr (#1027)
  ast/expressions.go
Labels: status/LGT2, type/4.0-cherry-pick, type/bug-fix
