Repository pingcap/parser, pull requests merged in 2021-01, with the labels that each got.

#1145 Revert "util: Add PrepareStmt into readOnly"
  ast/util.go
  ast/util_test.go
Labels: status/LGT2

#1146 yy_parser: enable supportWindowFunc by default (#986)
  yy_parser.go
Labels: status/LGT2

#1148 *: add a flag `RestoreWithDefaultDB` for Restore
  ast/dml.go
  format/format.go
Labels: status/LGT2, type/4.0-cherry-pick

#1161 parser: support builtin function SOUNDEX
  ast/functions.go
  ast/functions_test.go
Labels: first-time-contributor, status/LGT2
