Repository pingcap/parser, pull requests merged in 2021-02, with the labels that each got.

#1164 ast: support `explain format = 'test'` syntax
  ast/misc.go
  parser_test.go
Labels: needs-cherry-pick-4.0, status/LGT2, type/enhancement

#1163 README: add more resources
  README.md
Labels: status/LGT2, status/can-merge

#1167 parser: update the broken link for Contribution Guide in README.md
  README.md
Labels: first-time-contributor, status/LGT1

#1170 model: add a new TableInfoVersion for separating id allocators
  model/model.go
Labels: status/LGT2

#1172 model: add a version for the clustered index
  model/model.go
Labels: status/LGT2

#1151 lexer: quote identifier when get sql digest
  digester.go
  digester_test.go
Labels: status/LGT2, status/can-merge

#1176 digest: add missed backquote when getting digest
  digester.go
  digester_test.go
Labels: status/LGT2

#1173 restore: fix the bug about restore join table generate syntax error SQL
  ast/dml.go
  ast/dml_test.go
  format/format.go
  parser_test.go
Labels: status/LGT2
