Repository pingcap/parser, pull requests merged in 2021-03, with the labels that each got.

#1186 model: add ActionDropIndexes
  model/ddl.go
  model/model_test.go
Labels: first-time-contributor, status/LGT2

#1184 format: add RestoreStringWithoutCharset flag
  format/format.go
Labels: status/LGT2, status/can-merge

#1166 parser: regard NULL as literal when normalizing query
  digester.go
  digester_test.go
Labels: first-time-contributor, status/LGT2

#1182 privileges: show create view privilege should in `AllTablePrivs`
  mysql/const.go
Labels: status/LGT2

#1189 set right not null flag when newing extra PK
  model/model.go
  model/model_test.go
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge, type/bug-fix

#1193 downgrade mysql driver version
  go.mod
  go.sum
Labels: status/LGT2

#1197 auth: fix CheckScrambledPassword() panic for invalid input
  auth/auth.go
  auth/auth_test.go
Labels: status/LGT2, status/can-merge

#1199 auth: fix CheckScrambledPassword() panic for invalid input (#1197)
  auth/auth.go
  auth/auth_test.go
Labels: status/LGT2, type/4.0-cherry-pick

#1200 auth: fix CheckScrambledPassword() panic for invalid input (#1197)
  auth/auth.go
  auth/auth_test.go
Labels: status/LGT2, type/5.0-cherry-pick

#1201 mysql: add create_view to tables_priv
  mysql/const.go
Labels: status/LGT2, status/can-merge

#1198 mysql: small privileges refactor
  mysql/const.go
  mysql/const_test.go
  mysql/privs.go
  mysql/privs_test.go
Labels: status/LGT2, status/can-merge

#1202 mysql: modify TypeNewDecimal length in defaultLengthAndDecimalForCast
  ast/format_test.go
  mysql/util.go
Labels: status/LGT2
