Repository pingcap/parser, pull requests merged in 2021-09, with the labels that each got.

#1325 settings: Delete CODEOWNERS
  .github/CODEOWNERS
Labels: status/LGT2, status/can-merge

#1327 model: move placement policy definition into 2 parser
  model/model.go
Labels: status/LGT2, status/can-merge

#1323 Add 'auth_socket'
  ast/misc.go
  mysql/const.go
Labels: status/LGT2, status/can-merge

#1332 introduce a new Restore Flag RestoreBracketAroundBinaryOperation
  ast/expressions.go
  format/format.go
  parser_test.go
Labels: status/LGT2, status/can-merge

#1330 parser: move policyinfo test from tidb to parser
  go.mod
  model/model_test.go
Labels: status/LGT2, status/can-merge

#1341 ci: remove github action on pull request
  .github/workflows/itcase.yml
  .github/workflows/unittest.yml
Labels: status/LGT2, status/can-merge, first-time-contributor

#1340 add placement rules to schema and partition model
  model/model.go
Labels: status/LGT2

#1343 ast: fix a comment typo
  ast/base.go
Labels: status/LGT2, contribution, status/can-merge, first-time-contributor

#1345 mysql: fix MaxDurationWidthWithFsp
  mysql/const.go
Labels: status/LGT2

#1342 model: support database placement option and partition placement option
  model/ddl.go
Labels: status/LGT2, contribution, first-time-contributor

#1350 Implement interface for acquiring literal value
  lexer.go
  lexer_test.go
Labels: status/LGT2, status/can-merge

#1352 terror: provide a RegisterFinish API
  terror/terror.go
Labels: status/LGT2, status/can-merge
