Repository pingcap/parser, pull requests merged in 2021-07, with the labels that each got.

#1269 Fix issue with warning count for error 1068
  go.mod
  go.sum
Labels: status/LGT2

#1247 .github: migrate ci to GitHub Actions
  .github/workflows/itcase.yml
  .github/workflows/unittest.yml
  circle.yml
Labels: status/LGT2

#1275 Remove useless const AddIndexStr,AddPrimaryKeyStr
  model/ddl.go
Labels: status/LGT2

#1279 .github: migrate ci to GitHub Actions
  .github/workflows/itcase.yml
  .github/workflows/unittest.yml
  circle.yml
Labels: do-not-merge/cherry-pick-not-approved, size/L, status/LGT2

#1281 .github: migrate ci to GitHub Actions
  .github/workflows/itcase.yml
  .github/workflows/unittest.yml
  circle.yml
Labels: do-not-merge/cherry-pick-not-approved, size/L, status/LGT2

#1280 .github: migrate ci to GitHub Actions
  .github/workflows/itcase.yml
  .github/workflows/unittest.yml
  circle.yml
Labels: do-not-merge/cherry-pick-not-approved, size/L, status/LGT2

#1287 restore: support restoring SQL wrapping with TiDB special comments
  ast/ddl.go
  format/format.go
  format/format_test.go
  lexer.go
  lexer_test.go
  misc.go
  tidb/features.go
Labels: status/LGT2, status/can-merge
