Repository pingcap/parser, pull requests merged in 2021-08, with the labels that each got.

#1289 ast/functions: Add built-in function tidb_decode_sql_digests
  ast/functions.go
  parser_test.go
Labels: first-time-contributor, status/LGT2, status/can-merge

#1296 add special comments support for index constraints
  ast/ddl.go
  ast/ddl_test.go
Labels: first-time-contributor, status/LGT1

#1273 Model: add the new field to the Job Struct.
  model/ddl.go
Labels: status/LGT2, status/can-merge

#1301 support missing charset (#1140)
  charset/charset.go
  charset/charset_test.go
Labels: status/LGT2, contribution, first-time-contributor

#1286 ddl: add drop column with index flag
  mysql/type.go
Labels: status/LGT2

#1304 Added ReferencesPriv to DB and Table level, see tidb issue 26703
  mysql/privs.go
Labels: status/LGT2, status/can-merge, first-time-contributor

#1307 charset: sort the charset by its name
  charset/charset.go
Labels: status/LGT2, status/can-merge

#1316 Grant lock tables issue fix
  mysql/privs.go
Labels: status/LGT2, first-time-contributor

#1284 parser: Create SECURITY.md
  SECURITY.md
Labels: status/LGT2, status/can-merge, first-time-contributor

#1326 mysql: add customized release version config option
  mysql/const.go
Labels: status/LGT2
