Repository pingcap/parser, pull requests merged in 2021-06, with the labels that each got.

#1235 lexer: fix the bug that lexer may scan wrong tokens
  lexer.go
  parser_test.go
Labels: status/LGT2, type/5.0-cherry-pick

#1232 Caching sha2
  .gitignore
  auth/auth.go
  auth/auth_test.go
  auth/caching_sha2.go
  auth/caching_sha2_test.go
  auth/mysql_native_password.go
  auth/mysql_native_password_test.go
  mysql/const.go
  test.sh
Labels: status/LGT2, status/can-merge

#1241 CI: Use Go 1.16 instead of Go 1.13
  circle.yml
Labels: status/LGT2

#1244 *: fix cte restore for binding
  ast/dml.go
  format/format.go
  parser_test.go
Labels: needs-cherry-pick-5.1, status/LGT2

#1242 auth: Fix salt generation of caching_sha2_password
  auth/caching_sha2.go
  auth/caching_sha2_test.go
Labels: status/LGT2

#1245 *: fix cte restore for binding (#1244)
  ast/dml.go
  format/format.go
  parser_test.go
Labels: status/LGT2

#1246 auth: check for NUL in caching_sha2_password salt
  ast/misc.go
  auth/caching_sha2.go
  parser_test.go
Labels: status/LGT2

#1249 auth: caching_sha2_password salt fix
  auth/caching_sha2.go
  auth/caching_sha2_test.go
Labels: status/LGT2

#1260 Update dependencies
  go.mod
  go.sum
Labels: status/LGT2
